config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vaults do
    resources :links
  end
  root 'vaults#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :vault
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vaults
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vault.rb
class Vault < ActiveRecord::Base
  belongs_to :user
  has_many :links, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "auth"
    else
      "application"
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :set_vault
	before_action :set_link, except: [:create]

	def create
		@link = @vault.links.create(link_params)
		redirect_to @vault, notice: "Link created"
	end

	def destroy
		if @link.destroy
			flash[:success] = "Link was deleted."
		else
			flash[:error] = "Link could not be deleted."
		end
		redirect_to @vault
	end

	private

	def set_vault
		@vault = Vault.find(params[:vault_id])
	end

	def set_link
		@link = @vault.links.find(params[:id])
	end

	def link_params
		params[:link].permit(:link)
	end

end

app/controllers/vaults_controller.rb
class VaultsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vault, only: [:show, :edit, :update, :destroy]

  # GET /vaults
  # GET /vaults.json
  def index
    @vaults = current_user.vaults
  end

  # GET /vaults/1
  # GET /vaults/1.json
  def show
    @vaults = current_user.vaults
  end

  # GET /vaults/new
  def new
    @vaults = current_user.vaults
    @vault = current_user.vaults.build
  end

  # GET /vaults/1/edit
  def edit
    @vaults = current_user.vaults
  end

  # POST /vaults
  # POST /vaults.json
  def create
    @vault = current_user.vaults.build(vault_params)

    respond_to do |format|
      if @vault.save
        format.html { redirect_to @vault, notice: 'Vault was successfully created.' }
        format.json { render :show, status: :created, location: @vault }
      else
        format.html { render :new }
        format.json { render json: @vault.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vaults/1
  # PATCH/PUT /vaults/1.json
  def update
    respond_to do |format|
      if @vault.update(vault_params)
        format.html { redirect_to @vault, notice: 'Vault was successfully updated.' }
        format.json { render :show, status: :ok, location: @vault }
      else
        format.html { render :edit }
        format.json { render json: @vault.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vaults/1
  # DELETE /vaults/1.json
  def destroy
    @vault.destroy
    respond_to do |format|
      format.html { redirect_to vaults_url, notice: 'Vault was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vault
      @vault = Vault.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vault_params
      params.require(:vault).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkVaults</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Microlink SDK Vanilla/UMD bundle -->
  <script src="https://cdn.jsdelivr.net/npm/react@16/umd/react.production.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.production.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/styled-components@4/dist/styled-components.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@microlink/vanilla@4.0.0-alpha.3/dist/microlink.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= component "sidebar" do %>
    <%= component "logo" %>
    <%= component "nav" do %>
      <% @vaults.each do |vault| %>
        <%= component "link", link: vault, count: vault.links.count do %>
          <%= vault.name %>
        <% end %>
      <% end %>
      <div class="link__new">
        <%= component "link", link: new_vault_path do %>
          New Collection...
        <% end %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path, class: "" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "" %>
    <% end %>
  <% end %>
  <%= component "stage" do %>
    <%= component "container" do %>
      <%= yield %>
    <% end %>
  <% end %>
  <%= component "alert", id: "notice", message: notice %>
  <%= component "alert", id: "alert", message: alert %>
  <!-- Call microlink to replace links with cards previews -->
  <script>
    document.addEventListener("turbolinks:load", function (event) {
      microlink('.item__preview')
    })
    // Get the modal
    var modal = document.getElementById("add_modal");

    // Get the button that opens the modal
    var btn = document.getElementById("add_btn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("add__modal_close")[0];

    // When the user clicks the button, open the modal 
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
  </script>
</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkVaults</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Microlink SDK Vanilla/UMD bundle -->
  <script src="https://cdn.jsdelivr.net/npm/react@16/umd/react.production.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.production.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/styled-components@4/dist/styled-components.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@microlink/vanilla@4.0.0-alpha.3/dist/microlink.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="vault-body">
  <%= yield %>

  <p id="notice" class="notice <%= notice ? "notice-show" : ""%>"><%= notice %></p>
  <p id="alert" class="alert <%= alert ? "alert-show" : ""%>"><%= alert %></p>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for([@vault, @vault.links.build]) do |f| %>
  <%= f.text_field :link, placeholder: "New Link", class: "form-control" %>
  <%= f.submit %>
<% end %>

app/views/links/_link.html.erb
<%= component "item", link: link.link do %>
  <%= link_to vault_link_path(@vault, link.id), method: :delete, data: { confirm: "Are you sure?" }, class: "item__delete" do %>Delete<% end %>
<% end %>

app/views/vaults/_form.html.erb
<%= form_for(@vault) do |f| %>
  <% if @vault.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vault.errors.count, "error") %> prohibited this vault from being saved:</h2>

      <ul>
      <% @vault.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :name, placeholder: "Vault Name", class: "form-control" %>
  <%= f.submit %>
<% end %>

app/views/vaults/edit.html.erb
<div class="vault-heading media align-items-end">
  <div class="media-body"><%= render 'form' %></div>
</div>
<%= render @vault.links.order(created_at: :desc) %>

app/views/vaults/index.html.erb
<%= component "null" %>

app/views/vaults/new.html.erb
<%= component "form" do %>
  <%= render 'form' %>
<% end %>

app/views/vaults/show.html.erb
<%= component "add" %>
<%= component "heading" do %>
  <%= link_to edit_vault_path(@vault), class: "" do %>
    <h1><%= @vault.name %></h1>
  <% end %>
<% end %>
<% if @vault.links.count != 0 %>
  <%= render @vault.links.order(created_at: :desc) %>
<% else %>
  <%= component "null" %>
<% end %>
<%= link_to "Delete", @vault, method: :delete, data: { confirm: 'Are you sure?' }, class: "" %>